export const BUILDERTOOLS = [
  {
    id: 1,
    title: 'textbox',
    type: 'textbox',
    link: '',
  },
  {
    id: 2,
    title: 'password',
    type: 'textbox',
    link: '',
  },
  {
    id: 3,
    title: 'button',
    type: 'button',
    link: '',
  },
  {
    id: 4,
    title: 'buttongroup',
    type: 'buttongroup',
    link: '',
  },
  {
    id: 4,
    title: 'accordian',
    type: 'accordian',
    link: '',
  },
  {
    id: 5,
    title: 'checkbox',
    type: 'checkbox',
    link: '',
  },
  {
    id: 6,
    title: 'checkboxgroup',
    type: 'checkboxgroup',
    link: '',
  },
  {
    id: 7,
    title: 'dropdown',
    type: 'dropdown',
    link: '',
  },
  {
    id: 8,
    title: 'timeline',
    type: 'timeline',
    link: '',
  },
  {
    id: 9,
    title: 'alers',
    type: 'alers',
    link: '',
  },
  {
    id: 10,
    title: 'launcher',
    type: 'launcher',
    link: '',
  },
  {
    id: 11,
    title: 'avatar',
    type: 'avatar',
    link: '',
  },
  {
    id: 12,
    title: 'brand band',
    type: 'brand band',
    link: '',
  },
  {
    id: 13,
    title: 'breadcrumb',
    type: 'breadcrumb',
    link: '',
  },
  {
    id: 14,
    title: 'header',
    type: 'header',
    link: '',
  },
  {
    id: 15,
    title: 'buttongroup',
    type: 'buttongroup',
    link: '',
  },
  {
    id: 16,
    title: 'buttonicons',
    type: 'buttonicons',
    link: '',
  },
  {
    id: 17,
    title: 'cards',
    type: 'cards',
    link: '',
  },
  {
    id: 18,
    title: 'checkbox toggle',
    type: 'checkbox toggle',
    link: '',
  },
  {
    id: 19,
    title: 'color picker',
    type: 'color picker',
    link: '',
  },
  {
    id: 20,
    title: 'combobox',
    type: 'combobox',
    link: '',
  },
  {
    id: 21,
    title: 'counter',
    type: 'counter',
    link: '',
  },
  {
    id: 22,
    title: 'data tables',
    type: 'data tables',
    link: '',
  },
  {
    id: 23,
    title: 'datepickers',
    type: 'datepickers',
    link: '',
  },
  {
    id: 24,
    title: 'timeline',
    type: 'timeline',
    link: '',
  },
];
